/**
 * List of valid PMP tools and techniques
 * This list has been cleaned up to remove duplicates and standardize naming
 */
export const VALID_TOOLS = [
  "SWOT_analysis",
  "Team_Charter",
  "active_listening",
  "advertising",
  "affinity_diagrams",
  "alternatives_analysis",
  "analogous_estimating",
  "assumption_and_constraint_analysis",
  "audits",
  "autocratic_decision_making",
  "benchmarking",
  "bidder_conferences",
  "bottom_up_estimating",
  "brainstorming",
  "burndown_chart",
  "cause_and_effect_diagrams",
  "change_control_tools",
  "check_sheets",
  "checklists",
  "claims_administration",
  "colocation",
  "communication_methods",
  "communication_models",
  "communication_requirements_analysis",
  "communication_skills",
  "communication_technology",
  "conflict_management",
  "contracts",
  "control_charts",
  "cost_benefit_analysis",
  "critical_path_method",
  "cultural_awareness",
  "data_analysis",
  "data_gathering",
  "decision_making",
  "decomposition",
  "delphi_technique",
  "design_for_x",
  "document_analysis",
  "earned_value_analysis",
  "emotional_intelligence",
  "enterprise_environmental_factors_eefs",
  "expected_monetary_value_analysis",
  "expert_judgment",
  "facilitation",
  "flowcharts",
  "focus_groups",
  "group_decision_making_techniques",
  "hierarchical_charts",
  "histogram",
  "independent_cost_estimates",
  "influencing",
  "information_radiator",
  "inspections",
  "interpersonal_and_team_skills",
  "interviews",
  "kanban_board",
  "lead_and_lag",
  "leadership",
  "logical_data_model",
  "matrix_diagrams",
  "meeting_management",
  "meetings",
  "mind_mapping",
  "monte_carlo_simulation",
  "multicriteria_decision_analysis",
  "negotiation",
  "observation_conversation",
  "organizational_process_assets_opas",
  "parametric_estimating",
  "pareto_chart",
  "performance_reporting",
  "performance_reviews",
  "political_awareness",
  "pre_assignment",
  "probability_and_impact_matrix",
  "procurement_negotiation",
  "product_breakdown_structure",
  "progressive_elaboration",
  "project_management_information_system",
  "project_schedule_network_diagrams",
  "questionnaires_and_surveys",
  "raci_chart",
  "requirements_traceability_matrix",
  "reserve_analysis",
  "resource_leveling",
  "responsibility_assignment_matrix",
  "risk_data_quality_assessment",
  "risk_probability_and_impact_assessment",
  "rolling_wave_planning",
  "root_cause_analysis",
  "scatter_diagrams",
  "schedule_compression_fast_tracking_crashing",
  "scheduling_tools",
  "sensitivity_analysis",
  "source_selection_analysis",
  "source_selection_criteria",
  "stakeholder_analysis",
  "stakeholder_engagement_assessment_matrix",
  "tailoring",
  "team_building",
  "test_and_inspection_planning",
  "three_point_estimating",
  "trend_analysis",
  "value_stream_mapping",
  "variance_analysis",
  "virtual_teams",
  "voting",
  "what_if_scenario_analysis",
  "work_breakdown_structure"
] as const;

// Type for a valid tool
export type ValidTool = typeof VALID_TOOLS[number];

// Helper function to check if a string is a valid tool
export function isValidTool(tool: string): tool is ValidTool {
  return VALID_TOOLS.includes(tool as ValidTool);
}

// Helper function to get all tools for a specific category
export function getToolsByCategory(category: 'planning' | 'executing' | 'monitoring' | 'all'): readonly ValidTool[] {
  // This can be expanded later to categorize tools by their primary use
  return VALID_TOOLS;
} 